<template>
  <div>
    <h1>Help</h1>
    <div class="help-section">
      <h4>What is cmpct.io</h4>
      <spoiler title="What is cmpct.io">
        <p>cmpct.io is a free service that enables you to create shorter links to websites.</p>
        <p>We have features to protect people you send the link too, so unlike other platforms which scammers use to trick people, users see where the link goes before clicking.</p>
      </spoiler>
      <spoiler title="How does it work?">
        <p>Its simple, if you want to share a link with others, but the link is super long; pop it into cmpct.io and we will give you a shorter link that goes to the same place!</p>
      </spoiler>
      <spoiler title="Why bother?">
        <p>Long links are annoying, they clutter your chat with huge blocks of unreadable text.</p>
        <p>Using cmpct.io has other benefits too though!</p>
        <p>When you share a link generated by cmpct.io you are able to benefit from some cool social features, try it out!</p>
      </spoiler>
    </div>
    <div class="help-section">
      <h4>Privacy and safety?</h4>
      <spoiler title="How do you make money?">
        <p>We don't, this is a free service which generates no revenue, we don't sell or share your data with others either</p>
      </spoiler>
      <spoiler title="Is it safe?">
        <p>We believe our service is safer than other similiar websites because we operate slightly differently</p>
        <p>When you navigate to our links, you don't go straight to the website, but land on cmpct.io</p>
        <p>On cmpct.io you can post comments and report unsafe links, we also show you where the link will go</p>
      </spoiler>
      <spoiler title="What data do you collect?">
        <p>We don't want your personal information, we don't collect any. We only store a history of the links you visited on your device (so you can see it), and that is never transmitted to our servers</p>
        <p>cmpct.io is open source, you can review our code on our <a href="https://github.com/tommcclean/cmpct.io" target="blank">Github Repository</a></p>
      </spoiler>
    </div>
  </div>
</template>

<script>
import spoiler from '@/components/help/spoiler.vue'

export default {
  head () {
    return {
      title: this.$t('pageTitle')
    }
  },
  components: {
    spoiler
  }
}
</script>

<style scoped lang="scss">
  .help-section {
    display: inline-block;
    width: 49%;
    padding: 10px;
    max-width: 500px;

    @media (max-width: 768px) {
      width: 100%;
    }

    h4 {
      margin-bottom: 10px;
    }
  }
</style>

<i18n>
{
  "en": {
    "pageTitle": "cmpct.io: Help"
  },
  "fr": {
    "pageTitle": "cmpct.io: Aidez-moi"
  },
  "es": {
    "pageTitle": "cmpct.io: Ayuda"
  }
}
</i18n>
