<template>
  <container>
    <h1>Help</h1>
    <div class="help-section">
      <h4>What is cmpct.io</h4>
      <spoiler title="What is cmpct.io">
        <p>cmpct.io is a free service that enables you to create shorter links to websites.</p>
        <p>We have features to protect the people you send the link to, so unlike other platforms which scammers use to trick people, user's see where the link goes before going there.</p>
      </spoiler>
      <spoiler title="How does it work?">
        <p>Its simple, if you want to share a link with others, but the link is super long; pop it into cmpct.io and we will give you a shorter link that goes to the same place!</p>
      </spoiler>
      <spoiler title="Why bother?">
        <p>Long links are annoying, they clutter your chat with huge blocks of unreadable text.</p>
        <p>Using cmpct.io has other benefits too though!</p>
        <p>When you share a link generated by cmpct.io you are able to benefit from some cool social features, try it out!</p>
      </spoiler>
    </div>
    <div class="help-section">
      <h4>Privacy and safety?</h4>
      <spoiler title="How do you make money?">
        <p>We don't, this is a free service which generates no revenue, we don't sell or share your data with others either</p>
      </spoiler>
      <spoiler title="Is it safe?">
        <p>We believe our service is safer than other similiar websites because we operate slightly differently</p>
        <p>When you navigate to a shortened link, you don't go straight to the website, but land on cmpct.io</p>
        <p>On our landing page you can post comments and report unsafe links, we also show you where the link will go</p>
      </spoiler>
      <spoiler title="What data do you collect?">
        <p>We don't store any data showing who followed which links, we do store some anonymous analytics to show how popular a link is</p>
      </spoiler>
    </div>
  </container>
</template>

<script>
import container from '@/components/layout/container.vue'
import spoiler from '@/components/help/spoiler.vue'

export default {
  components: {
    container,
    spoiler
  }
}
</script>

<style scoped lang="scss">
  .help-section {
    display: inline-block;
    width: 49%;
    padding: 10px;
    max-width: 500px;

    @media (max-width: 768px) {
      width: 100%;
    }

    h4 {
      margin-bottom: 10px;
    }
  }
</style>
